# 14.2 예외처리와 스택 되감기





```C++

// main.cpp

#include <iostream>

// void last() throw(int)   int 예외를 던질 수도 있다. exception specifier


void last() {
    std::cout << "last " << std::endl;
    std::cout << "Throws exception " << std::endl;

    throw 'a';
    std::cout << "End last" << std::endl;
}

void third() {
    std::cout << "Third" << std::endl;

    last();
    std::cout << "End third" << std::endl;
}

void second() {
    std::cout << "Second" << std::endl;

    try {
        third();
    }
    catch (double) {
        std::cerr << "Second caught double exception " << std::endl;
    }

    std::cout << "End second" << std::endl;

}

void first() {
    std::cout << "First" << std::endl;

    try {
        second();
    }
    catch (int) {
        std::cerr << "first caught int exception" << std::endl;
    }

    std::cout << "End first" << std::endl;

}


int main() {

    std::cout << "Start" << std::endl;

    try {
        first();
    }
    catch (int) {
        std::cerr << "main caught int exception " << std::endl;
    }

        // uncaught exceptions
    catch (...)  // catch - all handlers
    {
        std::cerr << "main caught ellipses exception " << std::endl;
    }


    std::cout << "End main" << std::endl;


    return 0;
}

```

