# 14.5 함수 try



```C++

// main.cpp

#include <iostream>
#include <exception>
#include <string>

void doSomething() { // 가장 바깥 {} 생략 가능.
    try {
        throw -1;
    } catch (...) {
        std::cout << "Catch in doSomething()" << std::endl;
    }

}

class A {
private:
    int m_x;

public:
    A(int x) : m_x(x) {
        if (x <= 0)
            throw 1;
    }
};

class B : public A {
public:
//    B(int x) : A(x) {}

    B(int x) try : A(x) {
        // do initialization
    }
    catch (...) {
        std::cout << "Catch in B constructor " << std::endl;
        throw;
    }
};

int main() {

    try {
        B b(0);
    } catch (...) {
        std::cout << "Catch in main()" << std::endl;
    }


}

```

